# Pandas Library

### 1. Basics

In [1]:
import pandas as pd

In [2]:
path = r"students.csv"

In [3]:
df = pd.read_csv(path)

In [4]:
df

       name  age   regid  phy  chem  math  bio  avg  rank
0     Vijay   14  HPE001   99    98    97   36    0     0
1     Aryan   14  HPE002   98    61    93   96    0     0
2      Muni   14  HPE003   97    98    77   94    0     0
3      Abhi   14  HPE004   86    93    97   95    0     0
4   Hemanth   14  HPE005   94    91    93   96    0     0
5     Grace   14  HPE006   94    65    46   67    0     0
6    Ankita   14  CAP007   99    99    99   99    0     0
7      John   14  HPE008   96    93    77   85    0     0
8     Chris   14  HPE009   54    91    43   96    0     0
9     Grace   14  ORA006   67    95    96   87    0     0
10   Ankita   14  INF007   99    99    78   99    0     0

##### Working with Columns

In [5]:
df.columns

Index(['name', 'age', 'regid', 'phy', 'chem', 'math', 'bio', 'avg', 'rank'], dtype='str')

In [6]:
df.shape

(11, 9)

In [7]:
df.head()

      name  age   regid  phy  chem  math  bio  avg  rank
0    Vijay   14  HPE001   99    98    97   36    0     0
1    Aryan   14  HPE002   98    61    93   96    0     0
2     Muni   14  HPE003   97    98    77   94    0     0
3     Abhi   14  HPE004   86    93    97   95    0     0
4  Hemanth   14  HPE005   94    91    93   96    0     0

In [8]:
df.tail()

      name  age   regid  phy  chem  math  bio  avg  rank
6   Ankita   14  CAP007   99    99    99   99    0     0
7     John   14  HPE008   96    93    77   85    0     0
8    Chris   14  HPE009   54    91    43   96    0     0
9    Grace   14  ORA006   67    95    96   87    0     0
10  Ankita   14  INF007   99    99    78   99    0     0

In [9]:
df.describe()

        age        phy       chem       math        bio   avg  rank
count  11.0  11.000000  11.000000  11.000000  11.000000  11.0  11.0
mean   14.0  89.363636  89.363636  81.454545  86.363636   0.0   0.0
std     0.0  15.035110  13.403527  20.141319  19.090693   0.0   0.0
min    14.0  54.000000  61.000000  43.000000  36.000000   0.0   0.0
25%    14.0  90.000000  91.000000  77.000000  86.000000   0.0   0.0
50%    14.0  96.000000  93.000000  93.000000  95.000000   0.0   0.0
75%    14.0  98.500000  98.000000  96.500000  96.000000   0.0   0.0
max    14.0  99.000000  99.000000  99.000000  99.000000   0.0   0.0

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    11 non-null     str
 1   age     11 non-null     int64
 2   regid   11 non-null     str
 3   phy     11 non-null     int64
 4   chem    11 non-null     int64
 5   math    11 non-null     int64
 6   bio     11 non-null     int64
 7   avg     11 non-null     int64
 8   rank    11 non-null     int64
dtypes: int64(7), str(2)
memory usage: 1.0 KB

In [11]:
df['name']

0       Vijay
1       Aryan
2        Muni
3        Abhi
4     Hemanth
5       Grace
6      Ankita
7        John
8       Chris
9       Grace
10     Ankita
Name: name, dtype: str

In [12]:
df1 = df[['avg', 'name']]
df1

    avg     name
0     0    Vijay
1     0    Aryan
2     0     Muni
3     0     Abhi
4     0  Hemanth
5     0    Grace
6     0   Ankita
7     0     John
8     0    Chris
9     0    Grace
10    0   Ankita

In [13]:
# Creating a new column 'total' by summing up the scores of all subjects
df['total'] = df['phy'] + df['math'] + df['bio'] + df['chem']
df.head()

      name  age   regid  phy  chem  math  bio  avg  rank  total
0    Vijay   14  HPE001   99    98    97   36    0     0    330
1    Aryan   14  HPE002   98    61    93   96    0     0    348
2     Muni   14  HPE003   97    98    77   94    0     0    366
3     Abhi   14  HPE004   86    93    97   95    0     0    371
4  Hemanth   14  HPE005   94    91    93   96    0     0    374

In [14]:
# Dropping the 'total' column from the DataFrame - remove the column from the DataFrame
df2 = df.drop('total', axis = 1)
df2

       name  age   regid  phy  chem  math  bio  avg  rank
0     Vijay   14  HPE001   99    98    97   36    0     0
1     Aryan   14  HPE002   98    61    93   96    0     0
2      Muni   14  HPE003   97    98    77   94    0     0
3      Abhi   14  HPE004   86    93    97   95    0     0
4   Hemanth   14  HPE005   94    91    93   96    0     0
5     Grace   14  HPE006   94    65    46   67    0     0
6    Ankita   14  CAP007   99    99    99   99    0     0
7      John   14  HPE008   96    93    77   85    0     0
8     Chris   14  HPE009   54    91    43   96    0     0
9     Grace   14  ORA006   67    95    96   87    0     0
10   Ankita   14  INF007   99    99    78   99    0     0

In [15]:
df

       name  age   regid  phy  chem  math  bio  avg  rank  total
0     Vijay   14  HPE001   99    98    97   36    0     0    330
1     Aryan   14  HPE002   98    61    93   96    0     0    348
2      Muni   14  HPE003   97    98    77   94    0     0    366
3      Abhi   14  HPE004   86    93    97   95    0     0    371
4   Hemanth   14  HPE005   94    91    93   96    0     0    374
5     Grace   14  HPE006   94    65    46   67    0     0    272
6    Ankita   14  CAP007   99    99    99   99    0     0    396
7      John   14  HPE008   96    93    77   85    0     0    351
8     Chris   14  HPE009   54    91    43   96    0     0    284
9     Grace   14  ORA006   67    95    96   87    0     0    345
10   Ankita   14  INF007   99    99    78   99    0     0    375

In [16]:
df.drop('total', axis = 1, inplace = True)
df

       name  age   regid  phy  chem  math  bio  avg  rank
0     Vijay   14  HPE001   99    98    97   36    0     0
1     Aryan   14  HPE002   98    61    93   96    0     0
2      Muni   14  HPE003   97    98    77   94    0     0
3      Abhi   14  HPE004   86    93    97   95    0     0
4   Hemanth   14  HPE005   94    91    93   96    0     0
5     Grace   14  HPE006   94    65    46   67    0     0
6    Ankita   14  CAP007   99    99    99   99    0     0
7      John   14  HPE008   96    93    77   85    0     0
8     Chris   14  HPE009   54    91    43   96    0     0
9     Grace   14  ORA006   67    95    96   87    0     0
10   Ankita   14  INF007   99    99    78   99    0     0

##### Working with Rows

In [17]:
df.head()

      name  age   regid  phy  chem  math  bio  avg  rank
0    Vijay   14  HPE001   99    98    97   36    0     0
1    Aryan   14  HPE002   98    61    93   96    0     0
2     Muni   14  HPE003   97    98    77   94    0     0
3     Abhi   14  HPE004   86    93    97   95    0     0
4  Hemanth   14  HPE005   94    91    93   96    0     0

In [18]:
df.loc[2]

name       Muni
age          14
regid    HPE003
phy          97
chem         98
math         77
bio          94
avg           0
rank          0
Name: 2, dtype: object

In [19]:
# Selecting multiple rows using .loc - label-based indexing
df.loc[[4, 2, 1]] 
# First set the index to 'regid' column and then select rows using .loc
# df.set_index('regid', inplace = True)
# df.loc[['HPE001', 'HPE003', 'HPE002']]

      name  age   regid  phy  chem  math  bio  avg  rank
4  Hemanth   14  HPE005   94    91    93   96    0     0
2     Muni   14  HPE003   97    98    77   94    0     0
1    Aryan   14  HPE002   98    61    93   96    0     0

In [20]:
# Indexing using .iloc - position-based indexing
df3 = df.iloc[[3, 1, 3, 4, 7]] # Numeric index-based selection - numerical only
df3

      name  age   regid  phy  chem  math  bio  avg  rank
3     Abhi   14  HPE004   86    93    97   95    0     0
1    Aryan   14  HPE002   98    61    93   96    0     0
3     Abhi   14  HPE004   86    93    97   95    0     0
4  Hemanth   14  HPE005   94    91    93   96    0     0
7     John   14  HPE008   96    93    77   85    0     0

In [21]:
# Filtering rows where physics score is less than 95 and math score is less than 95 - condition-based filtering
df[(df['phy'] < 95) & (df['math'] < 95)]

      name  age   regid  phy  chem  math  bio  avg  rank
4  Hemanth   14  HPE005   94    91    93   96    0     0
5    Grace   14  HPE006   94    65    46   67    0     0
8    Chris   14  HPE009   54    91    43   96    0     0

### 2. Solving the Student Report Problem

In [22]:
import pandas as pd
df = pd.read_csv(r"students.csv")

In [23]:
df['avg'] = df[['phy', 'chem', 'math', 'bio']].mean(axis = 1)
df.head()

      name  age   regid  phy  chem  math  bio    avg  rank
0    Vijay   14  HPE001   99    98    97   36  82.50     0
1    Aryan   14  HPE002   98    61    93   96  87.00     0
2     Muni   14  HPE003   97    98    77   94  91.50     0
3     Abhi   14  HPE004   86    93    97   95  92.75     0
4  Hemanth   14  HPE005   94    91    93   96  93.50     0

In [24]:
df['rank'] = df['avg'].rank(ascending = False, method = 'dense')
df

       name  age   regid  phy  chem  math  bio    avg  rank
0     Vijay   14  HPE001   99    98    97   36  82.50   9.0
1     Aryan   14  HPE002   98    61    93   96  87.00   7.0
2      Muni   14  HPE003   97    98    77   94  91.50   5.0
3      Abhi   14  HPE004   86    93    97   95  92.75   4.0
4   Hemanth   14  HPE005   94    91    93   96  93.50   3.0
5     Grace   14  HPE006   94    65    46   67  68.00  11.0
6    Ankita   14  CAP007   99    99    99   99  99.00   1.0
7      John   14  HPE008   96    93    77   85  87.75   6.0
8     Chris   14  HPE009   54    91    43   96  71.00  10.0
9     Grace   14  ORA006   67    95    96   87  86.25   8.0
10   Ankita   14  INF007   99    99    78   99  93.75   2.0

In [25]:
df.to_json('student_report.json')

In [26]:
df.to_csv('student_report.csv', index = False)

In [27]:
df.to_excel('student_report.xlsx')

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    11 non-null     str
 1   age     11 non-null     int64
 2   regid   11 non-null     str
 3   phy     11 non-null     int64
 4   chem    11 non-null     int64
 5   math    11 non-null     int64
 6   bio     11 non-null     int64
 7   avg     11 non-null     float64
 8   rank    11 non-null     float64
dtypes: float64(2), int64(5), str(2)
memory usage: 1.0 KB